### ISSUE TITLE
2 questions about the INTERN

### ISSUE THREAD

**Issue by dev-sungman** [OpenGVLab/gv-benchmark#3]
Hello, 

First, thanks for releasing this great work !

I have 2 questions about the INTERN. 
The questions are as follows:
1.  What's the difference between UP-G det and UP-G cls ? 
    - according to the paper, there was a single benchmark score for UP-G.
    - however, in the released model and configuration, I could find the UP-G [cls](https://github.com/OpenGVLab/gv-benchmark/blob/ffe1f7460b857c88276d52a1537cbc673002f1e4/configs/cls/_base_/models/release/central_resnet50.py#L48), [det](https://github.com/OpenGVLab/gv-benchmark/blob/ffe1f7460b857c88276d52a1537cbc673002f1e4/configs/det/_base_/models/faster_rcnn_central_r50_fpn_intern.py#L49) model. 

2. Is backbone frozen when expert and general training?
-  Due to the amateur training, the backbone may have strong representation. Then, I think we don't have to train the backbone on amateur and expert sessions. Is it right?
- How can I check the detailed information about the training for each stage?

Thanks in advance.

**Comment by yinanhe** [comment]
1. They have different BN parameters that are friendly to different tasks. The loading method is the same.
2. Backbone is not frozen in the expert and generalist training stage while the task heads may be frozen.  The feature representation of backbone is continuously enhanced during 3 stages.

**Comment by dev-sungman** [comment]
Thanks very much for replying
